<!-- Copyright The OpenTelemetry Authors -->
<!-- SPDX-License-Identifier: Apache-2.0 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.opentelemetry.injector.test</groupId>
    <artifactId>jvm-integration-tests</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>no-op-agent</artifactId>
  <packaging>jar</packaging>

  <build>
    <finalName>no-op-agent</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <archive>
            <manifestEntries>
              <Premain-Class>io.opentelemetry.javaagent.NoOpAgent</Premain-Class>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
