dotnet_auto_instrumentation_agent_path_prefix=/custom/path/to/dotnet/instrumentation
dotnet_auto_instrumentation_minimum_dotnet_major_version=6
jvm_auto_instrumentation_agent_path=/custom/path/to/jvm/javaagent.jar
nodejs_auto_instrumentation_agent_path=/custom/path/to/nodejs/node_modules/@opentelemetry/auto-instrumentations-node/build/src/register.js
python_auto_instrumentation_agent_path_prefix=/custom/path/to/python
ruby_auto_instrumentation_agent_path_prefix=/custom/path/to/ruby
all_auto_instrumentation_agents_env_path=/custom/path/to/auto_instrumentation_env.conf
auto_instrumentation_disabled=nodejs
include_paths=/app/*,/home/user/test/*
include_paths=/another_dir/*
exclude_paths=/usr/*,/opt/*
exclude_paths=/another_excluded_dir/*
include_with_arguments=-jar,*my-app*,*.js
include_with_arguments=*.dll
exclude_with_arguments=-javaagent*,*@opentelemetry-js*
exclude_with_arguments=-debug
