name: build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-package:
    runs-on: ${{ matrix.ARCH == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        SYS_PACKAGE: [ "deb", "rpm" ]
        ARCH: [ "amd64", "arm64"]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run tests
        run: make tests ARCH=${{ matrix.ARCH }}

      - name: Build ${{ matrix.ARCH }} ${{ matrix.SYS_PACKAGE }} package
        run: make ${{ matrix.SYS_PACKAGE }}-package ARCH="${{ matrix.ARCH }}"

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: otelinject-${{ matrix.ARCH }}-${{ matrix.SYS_PACKAGE }}
          path: ./dist/*.${{ matrix.SYS_PACKAGE }}
  integration-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        lang: [ "java" ]
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Run integration tests for ${{ matrix.lang }}
        run: make integration-test-${{ matrix.lang }}
